# Generated by Django 6.1.1 on 2026-09-29 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('food_portion', models.PositiveIntegerField()),
                ('best_before', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('pickup_option', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('picture', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
